defaultEntryPoints = ["web", "web-secure"]

[log]
  level = "debug"

[api]
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"

[providers]
  [providers.docker] 
    swarmMode = true
    watch = true
    exposedbydefault = false
  [providers.file]
    watch = true
    directory = "/etc/traefik/"
    filename = "dynaefik.toml"