defaultEntryPoints = ["web", "web-secure"]

[log]
level = "info"

[api]
dashboard = true

[entryPoints]
  [entryPoints.web]
  address = ":80"
  [entryPoints.web-secure]
  address = ":443"

[providers]
  [providers.docker] 
  swarmMode = true
  watch = true
  exposedbydefault = false

[http.middlewares]
  [http.middlewares.global_http_to_https.redirectRegex]
    regex = "^http://(.*)"
    replacement = "https://$1"