defaultEntryPoints = ["web", "web-secure"]

[log]
level = "debug"

[api]
dashboard = true

[entryPoints]
  [entryPoints.web]
  address = ":80"
  [entryPoints.web-secure]
  address = ":443"

[http.middlewares]
  [http.middlewares.global-http-to-https.redirectRegex]
  regex = "^http://(.*)"
  replacement = "https://$1"

[providers]
  [providers.docker] 
  swarmMode = true
  watch = true
  exposedbydefault = false
