version: "3"
services:
  traefik:
    image: traefik:v2.0
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      # - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web-secure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
        - "traefik.http.routers.api.service=api@internal"
        # - "traefik.http.services.traefik_service.loadbalancer.server.port=8080"
        # 
        # - "traefik.http.middlewares.traefik_redirect.redirectregex.regex=^http://(.*)"
        # - "traefik.http.middlewares.traefik_redirect.redirectregex.replacement=https://$$1"
        # 
        # - "traefik.http.routers.traefik_insecure.rule=Host(`traefik.swarm.olst.io`)"
        # - "traefik.http.routers.traefik_insecure.entrypoints=web"
        # - "traefik.http.routers.traefik_insecure.middlewares=traefik_redirect"
        # 
        # - "traefik.http.routers.traefik_secure.rule=Host(`traefik.swarm.olst.io`)"
        # - "traefik.http.routers.traefik_secure.tls=true"
        # - "traefik.http.routers.traefik_secure.entrypoints=web-secure"
        # - "traefik.http.routers.traefik_dashboard.middlewares=traefik_dashbord_auth"
        # 
        # - "traefik.http.middlewares.traefik_dashbord_auth.basicauth.users=admin:$$apr1$$1I1ii04B$$HXp60s10NwWKeNsdgQ9xD/"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"