version: "3"
services:
  readerstandalone:
    image: efc:reader-1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # ##################################
        # Base service configuration
        - "traefik.enable=true"
        # ##################################
        # Service service configuration
        - "traefik.http.services.readerstandalone_service.loadbalancer.server.port=3000"
        # ##################################
        # Middlewares serviceconfiguration
        # ##################################
        # Insecure (http) router configuration
        - "traefik.http.routers.readerstandalone_insecure.rule=Host(`readerstandalone.swarm.olst.io`)"
        - "traefik.http.routers.readerstandalone_insecure.entrypoints=web"
        - "traefik.http.routers.readerstandalone_insecure.service=readerstandalone_service"

  reader:
    image: efc:reader-1
    volumes:
      - efc_node_demo:/efc/data/
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # ##################################
        # Base service configuration
        - "traefik.enable=true"
        # ##################################
        # Service service configuration
        - "traefik.http.services.reader_service.loadbalancer.server.port=3000"
        # ##################################
        # Middlewares serviceconfiguration
        # ##################################
        # Insecure (http) router configuration
        - "traefik.http.routers.reader_insecure.rule=Host(`reader.swarm.olst.io`)"
        - "traefik.http.routers.reader_insecure.entrypoints=web"
        - "traefik.http.routers.reader_insecure.service=reader_service"

  writer:
    image: efc:writer-1
    volumes:
      - efc_node_demo:/efc/data/
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        # ##################################
        # Base service configuration
        - "traefik.enable=true"
        # ##################################
        # Service service configuration
        - "traefik.http.services.writer_service.loadbalancer.server.port=3000"
        # ##################################
        # Middlewares serviceconfiguration
        # ##################################
        # Insecure (http) router configuration
        - "traefik.http.routers.writer_insecure.rule=Host(`writer.swarm.olst.io`)"
        - "traefik.http.routers.writer_insecure.entrypoints=web"
        - "traefik.http.routers.writer_insecure.service=writer_service"
volumes:
  efc_node_demo: